Improve assertion message in assertTableColumnNames
Previously, when list has wrong length, their contents were not provided
in the failure message:

    java.lang.AssertionError: lists don't have the same size expected [4] but found [5]

(cherry picked from commit 64e834d643aabf9162aaa4662b7ec6b100d3759b)