Fix query failure when schema predicate bigger than "max prefixes"
Before the change, querying `information_schema.tables` with
`table_schema IN ...` and more than "max prefixes" values (100 by
default) would fail with

```
com.google.common.base.VerifyException: calculatePrefixesWithTableName returned too many prefixes: 12
	at com.google.common.base.Verify.verify(Verify.java:154)
	at io.trino.connector.informationschema.InformationSchemaMetadata.getPrefixes(InformationSchemaMetadata.java:221)
	at io.trino.connector.informationschema.InformationSchemaMetadata.applyFilter(InformationSchemaMetadata.java:191)
	at io.trino.metadata.MetadataManager.applyFilter(MetadataManager.java:1943)
	at io.trino.tracing.TracingMetadata.applyFilter(TracingMetadata.java:929)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.pushFilterIntoTableScan(PushPredicateIntoTableScan.java:247)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:120)
	at io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:83)
	at io.trino.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:209)
```

(cherry picked from commit da507b9a322e618999e535bc07d923c6fb9f91e0)